---
title: "30DCC_22-08"
author: "Christian Gebhard"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## prepare data

```{r}
library(tidyverse)
library(ggtext)
# library(MetBrewer)
# library(patchwork)
library(ggdark)
library(ggdist)

# Load custom fonts
library(showtext)
font_add_google("League Spartan")
showtext_auto()
```



## Penguins

```{r}


# load data, remove few NAs
library(palmerpenguins)
penguins_clean <- penguins |> 
  drop_na()

# bring into long form
penguins_tidy <- penguins_clean |> 
  pivot_longer(cols = c(flipper_length_mm, bill_length_mm, bill_depth_mm, body_mass_g), names_to = "measure", values_to = "value")  |> 
  mutate(
    measure = case_when(
      measure == "flipper_length_mm" ~ "Flipper length [mm]",
      measure == "bill_length_mm" ~ "Bill length [mm]",
      measure == "body_mass_g" ~ "Body mass [g]",
      measure == "bill_depth_mm" ~ "Bill depth [mm]"
    )
  )
  
```


```{r}

peng_plot <- ggplot(penguins_tidy, aes(x = value)) +
  geom_density(
    adjust = 1/2,
    fill = "white",
    alpha = 0.4) +
  labs(
    title = "<b>Peak Density</b>",
    subtitle = "The kernel density estimate plots of body measurements in the {palmerpenguins} package<br>resemble different shapes of 'mountain ridges'.",
    caption = "<br><span>DataViz by @c_gebhard | <b>#30DayChartChallenge, Day 07</b></span><span><br>Data: Horst AM, Hill AP, Gorman KB (2020). palmerpenguins:<br>Palmer Archipelago (Antarctica) penguin data. R package version 0.1.0. doi: 10.5281/zenodo.3960218</span>"
  ) +
  facet_wrap(~measure, nrow = 2, scales = "free", strip.position = "top") +
  theme_minimal() +
  dark_mode() +
  theme(
    plot.background = element_rect(color = "#333333"),
    panel.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_markdown(family = "League Spartan", size = 64),
    plot.subtitle = element_markdown(family = "League Spartan", size = 32, lineheight = 0.4),
    strip.background = element_blank(),
    strip.text = element_markdown(family = "League Spartan", size = 24),
    axis.title = element_blank(),
    axis.text.x = element_markdown(family = "League Spartan", size = 20),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.caption = element_markdown(family = "League Spartan", size = 20, lineheight = 0.4)
    )

ggsave(here::here("..", "plots", "2022_08.png"), plot = peng_plot, height = 5.5, width = 5.5, dpi = "retina")


```
