---
title: "30DCC_22-12"
author: "Christian Gebhard"
date: "26 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## prepare data

```{r}
library(tidyverse)
library(ggtext)
library(MetBrewer)
library(patchwork)
library(ggdist)
library(geomtextpath)

library(showtext)
font_add_google("Asap Condensed")
font_add_google("Asap")
font_add_google("Martel")
showtext_auto()

library(ggpubr)
```


```{r}
library(readr)
populations <- read_csv("../data/owid/urban-and-rural-population.csv") |> 
  janitor::clean_names() |> 
  pivot_longer(c(urban_population, rural_population), names_to = "area", values_to = "population") |> 
  filter(!is.na(code)) |> 
  filter(str_detect(code, pattern = "OWID", negate = TRUE)) |> 
  group_by(area, year) |> 
  summarise(population_sum = sum(population)) |> 
  ungroup() |> 
  mutate(
    pop_bil = population_sum / 1000000000,
    label = ifelse(area == "urban_population", "Urban population", "Rural population"),
    size = ifelse(area == "urban_population", 1, 0.5)
  )


## define annotations

line_data <- tribble(
  ~label, ~color, ~size,
  "Urban population", "#F6423C", 1,
  "Rural population", "#1F2E7A", 0.5
)

annotation_data <- tribble(
  ~x, ~y, ~label, ~hjust,
  2007, 3.33, "<span style='font-size:16pt'>Urban population overtakes rural population in 2007.</span>", 0,
  1998, 4.5, "<span style='font-size: 16pt;color: #AAAAAA;'><b>1999</b><br>World population<br>reaches 6 bn</span>", 1
)

```

```{r}

x_ticks <- c("1960", "", "", "", "", "", "", "", "", "", "1970", "", "", "", "", "", "", "", "", "", "1980", "", "", "", "", "1985", "", "", "", "", "1990", "", "", "", "", "1995", "", "", "", "", "2000", "", "", "", "", "2005", "", "", "", "", "2010", "", "", "", "", "2015", "", "", "", "", "2020", "", "")

econ <- ggplot(populations) +
  aes(
    x = year,
    y = pop_bil,
    color = area,
    # size = size,
    label = label
    ) +
  geom_line(
    # position = "identity",
    # alpha = 0.5
  ) +
  scale_y_continuous(
    limits = c(0, 5),
    position = "right",
    breaks = c(0, 1, 2, 3, 4, 5),
    labels = c("0", "1bn", "2bn", "3bn", "4bn", "5bn"),
    expand = expansion(mult = c(0, 0.1))
  ) +
  scale_x_continuous(
    expand = expansion(mult = c(0.01, 0)),
    breaks = c(seq(from = 1960, to = 2022)),
    labels = x_ticks
  ) +
  labs(
    title = "Global Urbanization",
    subtitle = "Since 2007 more than half of the world's population lives in <span style='color: #E3120B;'><b>urban areas</b></span>.<br>Before that, the majority lived in <span style='color: #1F2E7A;'><b>rural areas</b></span>. As the definition of 'urban' may<br>vary across countries, global estimations are difficult and somewhat debated.",
    caption = "<br>Data: World Bank based on World Population Prospects - UN Population Division (2018), via ourworldindata.org/urbanization<br><span>DataViz by @c_gebhard after @TheEconomist style guide | <b>#30DayChartChallenge, Day 12</b></span>",
  ) +
  geom_vline(
    xintercept = 1988,
    size = 0.1
  ) +
  annotate(
    geom = "richtext",
    label = "<span style='font-family: Asap Condensed; font-size: 26pt;color: #AAAAAA;'><b>1988</b><br>World population<br>reaches 5 bn</span>",
    x = 1987.8,
    y = 4.6,
    fill = NA,
    label.colour = NA,
    hjust = 1,
    lineheight = 0.8
  ) +
  geom_vline(
    xintercept = 2012,
    size = 0.1
  ) +
  annotate(
    geom = "richtext",
    label = "<span style='font-family: Asap Condensed; font-size: 26pt;color: #AAAAAA;'><b>2012</b><br>World population<br>reaches 7 bn</span>",
    x = 2011.8,
    y = 4.6,
    fill = NA,
    label.colour = NA,
    hjust = 1,
    lineheight = 0.8
  ) +
  annotate(
    geom = "curve", x = 2007.3, y = 2.8, xend = 2007.3, yend = 3.25, 
    curvature = .3, arrow = arrow(length = unit(1.2, "mm"))
  ) +
  annotate(
    geom = "richtext",
    label = "<span style='font-family: Asap Condensed; font-size: 26pt;color: #000000;'><b>2007</b><br>More people live<br>in urban areas</span>",
    x = 2001,
    y = 2.5,
    fill = NA,
    label.colour = NA,
    hjust = 0,
    lineheight = 0.8
  ) +
  scale_color_manual(values = c("#1F2E7A", "#F6423C")) +
  theme_classic() +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.major.y = element_line(color = "#EEEEEE", size = 0.5),
    legend.position = "none",
    axis.text.y.right = element_markdown(vjust = -0.2, hjust = 0, size = 26, colour = "#000000", family = "Asap Condensed"),
    axis.text.x = element_markdown(size = 26, colour = "#000000", family = "Asap Condensed"),
    axis.ticks.length.y.right = unit(15, "pt"),
    axis.ticks.y.right = element_line(color = "#EEEEEE", size = 0.5),
    axis.line.y.right = element_blank(),
    axis.title = element_blank(),
    plot.title = element_markdown(family = "Martel", face = "bold", size = 36),
    plot.title.position = "plot",
    plot.subtitle = element_markdown(family = "Martel", size = 32, lineheight = 0.4),
    plot.caption = element_markdown(family = "Martel", size = 20, lineheight = 0.4),
    plot.caption.position = "plot"
  )

ggsave(here::here("..", "plots", "2022_12_dist_econ.png"), plot = econ, height = 4, width = 5.5, dpi = "retina")

```