---
title: "30DCC_22-07"
author: "Christian Gebhard"
date: "26 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data source:

Tobias et al 2022 Ecology Letters
https://doi.org/10.6084/m9.figshare.16586228.v5

## prepare data

```{r}
library(tidyverse)
library(ggtext)
library(MetBrewer)
library(patchwork)
library(ggdist)

library(showtext)
font_add_google("Playfair Display")
font_add_google("Lato")
showtext_auto()
```

## load data



```{r}
library(readxl)
AVONET_Supplementary_dataset_1 <- read_excel("../data/avonet/AVONET Supplementary dataset 1.xlsx", 
    sheet = "AVONET3_BirdTree") 

avonet3 <- AVONET_Supplementary_dataset_1|> 
  janitor::clean_names() |> 
  mutate(habitat = ifelse(habitat == "NA", "not categorized", habitat)) |> 
  group_by(habitat) |> 
  mutate(
    wing_median = median(wing_length, na.rm = TRUE)
  ) |> 
  ungroup()

```   

```{r}
dplot <- ggplot(avonet3, aes(x = reorder(habitat, wing_median), y = wing_length, color = reorder(habitat, wing_median), fill = reorder(habitat, wing_median))) +
  ggdist::stat_halfeye(
    adjust = .5, 
    width = .6, 
    .width = 0, 
    justification = -.3, 
    point_colour = NA,
    alpha = 0.85) + 
  geom_boxplot(
    width = .25, 
    outlier.shape = NA,
    alpha = 0.5
  ) +
  geom_point(
    size = 0.5,
    alpha = 0.2,
    position = position_jitter(
      seed = 1, width = .1
    ),
    shape = 20
  ) +
  coord_flip() +
  scale_color_manual(values = met.brewer("Hokusai3", n = 12, type = "continuous")) +
  scale_fill_manual(values = met.brewer("Hokusai3", n = 12, type = "continuous")) +
  labs(
    title = "Birds of A Feather",
    subtitle = "Coastal and Marine bird species tend to have longer wings with median lengths<br>of 264.8mm and 253mm respectively. The longest wings, however are<br>found in other habitats.",
    y = "<b>Wing length [mm]</b>",
    caption = "<span><br>Data: 'AVONET' by Tobias et. al. 2022, doi:10.1111/ele.13898</span><br><span>DataViz by @c_gebhard | <b>#30DayChartChallenge, Day 07</b></span>"
  ) +
  theme_classic() +
  theme(
    legend.position = "none",
    axis.line = element_blank(),
    axis.ticks = element_blank(),
    panel.grid.major.x = element_line(colour = "#aaaaaa", size = 0.1),
    plot.title.position = "plot",
    plot.title = element_markdown(family = "Playfair Display", size = 72),
    plot.subtitle = element_markdown(family = "Lato", size = 32, lineheight = 0.4),
    axis.title.y = element_blank(),
    axis.title.x = element_markdown(family = "Lato", size = 20),
    axis.text = element_markdown(family = "Lato", size = 20),
    axis.text.y = element_markdown(face = "bold"),
    plot.caption = element_markdown(family = "Lato", size = 20, lineheight = 0.4)
  )

ggsave(here::here("..", "plots", "2022_07.png"), plot = dplot, height = 6, width = 5, dpi = "retina")


```