---
title: "30DCC_22-11.Rmd"
author: "Christian Gebhard"
date: "28 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggtext)
library(MetBrewer)
library(patchwork)
library(ggdist)
library(geomtextpath)

library(showtext)
font_add_google("Bitter")
font_add_google("Open Sans")
showtext_auto()
```


```{r}
library(climateR)
library(AOI)
```


```{r}
# get NYC data
nyc <- AOI::geocode('New York City', pt = TRUE)
nyc_prcp <- getGridMET(nyc, 
                  param = "prcp", 
                  startDate = "2021-01-01", endDate = "2021-12-31") 
# assign city label
nyc_prcp <- nyc_prcp |> 
  mutate(city = "New York City")

# get San Diego data
sdiego <- AOI::geocode('San Diego', pt = TRUE)
sdiego_prcp <- getGridMET(sdiego, 
                  param = "prcp", 
                  startDate = "2021-01-01", endDate = "2021-12-31")
# assign city label
sdiego_prcp <- sdiego_prcp |> 
  mutate(city = "San Diego")

# get Seattle data
seattle <- AOI::geocode('Seattle', pt = TRUE)
seattle_prcp <- getGridMET(seattle, 
                  param = "prcp", 
                  startDate = "2021-01-01", endDate = "2021-12-31")
# assign city label
seattle_prcp <- seattle_prcp |> 
  mutate(city = "Seattle")

# get Minneapolis data
minneapolis <- AOI::geocode('Minneapolis', pt = TRUE)
minneapolis_prcp <- getGridMET(minneapolis, 
                  param = "prcp", 
                  startDate = "2021-01-01", endDate = "2021-12-31")
# assign city label
minneapolis_prcp <- minneapolis_prcp |> 
  mutate(city = "Minneapolis")

# combine all four city datasets to one long dataframe
precip <- rbind(
  nyc_prcp, sdiego_prcp, seattle_prcp, minneapolis_prcp
) 

```

```{r}
# manually create annotation data, with months indicating quartals and city labales for facetting
label_data <- tribble(
  ~date, ~label, ~city,
  "2021-01-01", "January","Minneapolis",
  "2021-04-01", "April","Minneapolis",
  "2021-07-01", "July","Minneapolis",
  "2021-10-01", "October","Minneapolis",
  "2021-01-01", "January","Seattle",
  "2021-04-01", "April","Seattle",
  "2021-07-01", "July","Seattle",
  "2021-10-01", "October","Seattle",
  "2021-01-01", "January","San Diego",
  "2021-04-01", "April","San Diego",
  "2021-07-01", "July","San Diego",
  "2021-10-01", "October","San Diego",
  "2021-01-01", "January","New York City",
  "2021-04-01", "April","New York City",
  "2021-07-01", "July","New York City",
  "2021-10-01", "October","New York City"
) |> 
  mutate(date = as.Date(date))
  
```


```{r}

preplot <- ggplot(precip) +
  aes(x = date, y = prcp, fill = city) +
  geom_bar(alpha = 1, stat = "identity", size =1) +
  scale_y_continuous(
    trans = "pseudo_log",
    breaks = c(0, 10, 50, 150),
    labels = as.character(c(0, 10, 50, 150))
  ) +
  scale_fill_met_d("Egypt") +
  coord_polar(theta = "x") +
  facet_wrap(~ city, nrow = 2) +
  labs(
    title = "<b>Daily Precipitation 2021</b>",
    subtitle = "Within the four randomly selected cities, New York City recorded<br>the highest daily precipitation values. While NYC and Minneapolis<br>had precipitation throughout the year, the West Coast seems<br>to have a focus on the winter months.",
    caption = "Data: gridMET by Abatzoglou et. al., 2013, doi: 10.1002/joc.3413<br><span>DataViz by @c_gebhard | <b>#30DayChartChallenge, Day 11</b></span>",
    y = "<b>Daily Precipitation</b><br>[mm, pseudo-log transformed]"
  ) +
  theme_classic() +
  theme(
    panel.background = element_blank(),
    plot.title.position = "plot",
    plot.title = element_markdown(family = "Bitter", size = 64),
    plot.subtitle = element_markdown(family = "Open Sans", size = 30, lineheight = 0.4),
    strip.background = element_blank(),
    strip.text = element_markdown(family = "Bitter", size = 24),
    axis.title.x = element_blank(),
    axis.title.y = element_markdown(family = "Open Sans", size = 20, lineheight = 0.4),
    axis.line = element_blank(),
    panel.grid.major.x = element_line(color = "#DDDDDD"),
    panel.grid.major.y = element_line(color = "#EEEEEE"),
    axis.text = element_markdown(family = "Open Sans", size = 20),
    axis.ticks.y = element_blank(),
    plot.caption = element_markdown(family = "Open Sans", size = 20, lineheight = 0.4),
    legend.position = "none"
    )

ggsave(here::here("..", "plots", "2022_11.png"), plot = preplot, height = 5.5, width = 4, dpi = "retina")

```

