---
title: "30DCC_22-06"
author: "Christian Gebhard"
date: "25 3 2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ggtext)
library(MetBrewer)
library(patchwork)
library(ggwaffle)

library(showtext)
font_add('fa-solid', '../fonts/Font Awesome 6 Free-Solid-900.otf')
font_add('neue-black', '../fonts/TheNeue-Black.otf')
font_add_google("Sora")
showtext_auto()
```

## notes
Income classification acc. to: https://datatopics.worldbank.org/world-development-indicators/stories/the-classification-of-countries-by-income.html

Definitions: https://ourworldindata.org/water-access#definitions


## create data based on OWID data

```{r}

# compose data frames for high income countries according to OWID graph
water_high <- tribble(
  ~category, ~fraction,
  "Safely Managed", 98,
  "Basic", 2,
  "Limited", 0,
  "Unimproved", 0,
  "No Access", 0
)|> 
  mutate(
    drops = round(fraction *2 /10),
    category = factor(category),
    category = fct_relevel(category,c("Safely Managed","Basic","Limited", "Unimproved", "No Access"))
  )

# compose data frames for low income countries according to OWID graph
water_low <- tribble(
  ~category, ~fraction,
  "Safely Managed", 29,
  "Basic", 30,
  "Limited", 18,
  "Unimproved", 17,
  "No Access", 6
) |> 
  mutate(
    drops = round(fraction *2 /10),
    category = factor(category),
    category = fct_relevel(category,c("Safely Managed","Basic","Limited", "Unimproved", "No Access"))
  )


```

## convert to waffle data



```{r}
drops_low <- water_low |> 
  select(-fraction) |> 
  uncount(drops) 

drops_high <- water_high |> 
  select(-fraction) |> 
  uncount(drops) 

# create color values lookup by providing fontawesome drop-icons, coloured for each category.
drop_colors <- tibble(
  category = as.factor(c(1, 2, 3, 4, 5)), 
  label = c(
    "<span style='font-family:fa-solid; color: #376795'>&#xf043;</span>",
    "<span style='font-family:fa-solid; color: #aadce0'>&#xf043;</span>",
    "<span style='font-family:fa-solid; color: #ffd06f'>&#xf043;</span>",
    "<span style='font-family:fa-solid; color: #f7aa58'>&#xf043;</span>",
    "<span style='font-family:fa-solid; color: #e76254'>&#xf043;</span>"
  )
) |> 
  mutate(category = as.factor(category))

# generate waffle grid (ggwaffle package). This places the future icons on a 2-row/10 columns waffle grid.
# The next step joins the drop-colour lookup tibble to the icon positions according to the respective water access category
waffle_low <- waffle_iron(drops_low, aes_d(group = category), sample_size = 1, rows = 2) |> 
  mutate(group = as.factor(group),
         y = 1) |> 
  left_join(drop_colors, by = c("group" = "category"))

# the same is done for the high income countries
waffle_high <- waffle_iron(drops_high, aes_d(group = category), sample_size = 1, rows = 2) |> 
  mutate(group = as.factor(group),
         y = 1) |> 
  left_join(drop_colors, by = c("group" = "category"))
```

```{r}
# in the plot, the two waffle grids are plotted as richtext labels, then coordinate axes are flipped, so the two waffle grids now are next to each others with drops arranged from the top to the bottom.
# a jitter is added to the drop positions (via the ggbeeswarm package) to give a randomly dripping impression.

# first the low income waffle grid is plotted
plow <- ggplot(waffle_low) +
  geom_richtext(
    mapping = aes(
      x = x,
      y = y,
      label = label
    ),
    position = ggbeeswarm::position_quasirandom(groupOnX = FALSE, method = "quasirandom"),
    label.colour = NA, 
    fill = NA,
    size = 12,
    hjust = 0.5
  ) +
  coord_flip() + 
  scale_x_reverse(
    limits = c(11, 0)
  ) +
  scale_y_continuous(
    breaks = c(1, 2),
    limits = c(0.5, 1.5)
  ) +
  theme_void()
  

# next, the high income countries are plotted
phigh <- ggplot(waffle_high) +
  geom_richtext(
    mapping = aes(
      x = x,
      y = y,
      label = label
    ),
    position = ggbeeswarm::position_quasirandom(groupOnX = FALSE, method = "quasirandom"),
    label.colour = NA, 
    fill = NA,
    size = 12,
    hjust = 0.5
  ) +
  coord_flip() + 
  scale_x_reverse(
    limits = c(11, 0)
  ) +
  scale_y_continuous(
    breaks = c(1, 2),
    limits = c(0.5, 1.5)
  ) +
  theme_void()

# an annotation dataframe is created with coordinates and label of each annotation.
owid_ann <- tribble(
  ~x, ~y, ~label,
  28, 45, "<span style='font-family:Sora; size:6pt; color:#aadce0'><30 mins to collect</span>",
  28, 30, "<span style='font-family:Sora; size:6pt; color:#ffd06f;'>>30 mins to collect</span>",
  28, 20, "<span style='font-family:Sora; size:6pt; color:#f7aa58;'>Unprotected</span>",
  28, 16, "<span style='font-family:Sora; size:6pt; color:#f7aa58;'>dug well/spring</span>",
  28, 6, "<span style='font-family:Sora; size:6pt; color:#e76254;'>Surface water</span>",
  28, 2, "<span style='font-family:Sora; size:6pt; color:#e76254;'>only</span>",
  70, 9, "<span style='font-family:Sora; size:6pt; color:#376795;'>Less than 2.5% do</span>",
  70, 5, "<span style='font-family:Sora; size:6pt; color:#376795;'>not have access to</span>",
  70, 1, "<span style='font-family:Sora; size:6pt; color:#376795;'>safe drinking water.</span>"
)
  
# a background plot is created with the title, subtitle and caption
back_plot <- ggplot() +
  labs(
    title = "WATERSHED",
    subtitle = "Merely 6 out of 20 people in <b>low-income countries</b> have access to<br><span style='color:#376795;'><b>safe drinking water<b></span>, defined as: available when needed, located on<br>premises and free from contamination. Large parts have either access<br>to an improved yet remote source or even only unprotected, unsafe sources.<br>Each <span style='font-family:fa-solid; color: #000000'>&#xf043;</span> = 5% of the population within the respective income category.",
    caption = "<span>Gross National Income (GNI): constant internat. $<br>adj. for inflation and price differences between countries</span><br><span>DataViz by @c_gebhard | <b>#30DayChartChallenge, Day 06</b> | Data by & further reading at ourworldindata.org/water-access</span>"
  ) +
  scale_x_continuous(
    limits = c(0,100)
  ) +
  scale_y_continuous(
    limits = c(0,100)
  ) +
  theme_minimal() +
  theme(
    text = element_text(family = "Sora", lineheight = 0.4),
    plot.title = element_markdown(family = "neue-black", size = 72),
    plot.subtitle = element_markdown(family = "Sora", size = 34, lineheight = 0.4),
    plot.caption = element_markdown(family = "Sora", size = 20),
    panel.grid = element_blank(),
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  geom_richtext(
    data = owid_ann,
    aes(
      x = x,
      y = y,
      label = label
    ),
    label.colour = NA, 
    fill = NA,
    size = 12,
    hjust = 0
  ) +
  annotate(
    geom = "curve", x = 26, y = 5, xend = 15, yend = 12, 
    curvature = -.3, arrow = arrow(length = unit(2, "mm"))
  )


```


```{r}

# the two water faucets and GNI amounts were composed in inkscape and stored as PNG image.
# the image is read to be included above the water drop plots.
library("png")
highlow <- readPNG("assets/high_low.png", native = TRUE)

# via {patchwork} the water faucet image and the two drop-plots are placed on the background plot
patched <- back_plot +
  inset_element(
    p = highlow, 
    left = 0.02, 
    right = 0.98,
    top = 1,
    bottom = 0.8
  ) +
  inset_element(
    p = plow, 
    left = 0.1, 
    right = 0.3,
    top = 0.8,
    bottom = 0.1
  ) +
  inset_element(
    p = phigh, 
    left = 0.7, 
    right = 0.9,
    top = 0.8,
    bottom = 0.1
  ) 

#ggsave stores the final plot to file
ggsave(here::here("..", "plots", "2022_06.png"), plot = patched, height = 6, width = 6, dpi = "retina")

```

